=== Bleedmagic/xml-based-fhlc/src/schema/admission.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="admissions">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="page" type="xs:string" />
        <xs:element name="cards">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="card">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="icon" type="xs:string" />
                    <xs:element name="text" type="xs:string" />
                    <xs:element name="link" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Bleedmagic/xml-based-fhlc/src/data/public/admission.xml
<?xml version="1.0" encoding="UTF-8"?>
<admissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../schema/admission.xsd">
  <page>admission</page>
  <cards>
    <card>
      <icon>bi-gear-wide-connected</icon>
      <text>Enrollment Process For New Students</text>
      <link>newstudents.php</link>
    </card>
    <card>
      <icon>bi-file-earmark-text</icon>
      <text>Enrollment Process For Current Students</text>
      <link>currentstudents.php</link>
    </card>
    <card>
      <icon>bi-file-earmark-check</icon>
      <text>Grade Levels Offered</text>
      <link>gradelevels.php</link>
    </card>
    <card>
      <icon>bi-patch-plus</icon>
      <text>Requirements for New Applicants</text>
      <link>requirements.php</link>
    </card>
  </cards>
</admissions>
