=== Bleedmagic/xml-based-fhlc/src/schema/gradelevels.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="gradeLevels">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="section">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="image" type="xs:string" />
              <xs:element name="levels">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="level" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="type" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Bleedmagic/xml-based-fhlc/src/data/public/gradelevels.xml
<?xml version="1.0" encoding="UTF-8"?>
<gradeLevels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../schema/gradelevels.xsd">
  <section type="Preschool">
    <image>../../assets/img/nursery.png</image>
    <levels>
      <level>Nursery</level>
      <level>Kindergarten 1 </level>
      <level>Kindergarten 2 </level>
    </levels>
  </section>
  <section type="Elementary">
    <image>../../assets/img/elementary.png</image>
    <levels>
      <level>Grade 1</level>
      <level>Grade 2</level>
      <level>Grade 3</level>
      <level>Grade 4</level>
      <level>Grade 5</level>
      <level>Grade 6</level>
    </levels>
  </section>
</gradeLevels>
