=== Bleedmagic/xml-based-fhlc/src/schema/login.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="login">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="page">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="logo" type="xs:string" />
              <xs:element name="decorative-image" type="xs:string" />
              <xs:element name="title" type="xs:string" />
              <xs:element name="description" type="xs:string" />
              <xs:element name="checkbox">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="a">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="href" type="xs:string" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="forgot-password">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="a">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="href" type="xs:string" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="call-to-action">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="a">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="href" type="xs:string" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Bleedmagic/xml-based-fhlc/src/data/public/login.xml
<?xml version="1.0" encoding="UTF-8"?>
<login xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../schema/login.xsd">
  <page>
    <logo>../../../assets/img/fhlc-logo.png</logo>
    <decorative-image>../../../assets/img/login.jpg</decorative-image>
    <title>Sign in to Account</title>
    <description>Enter your username and password</description>
    <checkbox> I have carefully read and fully agree to the <a href="../terms-conditions.php" target="_blank">Terms
      and Conditions</a> and <a href="../privacy-policy.php" target="_blank">Privacy Policy</a> of this website.</checkbox>
    <forgot-password>
      <a href="forgot-password.php">Forgot Password?</a>
    </forgot-password>
    <call-to-action>Don't have an account? <a href="register.php">Register now!</a></call-to-action>
  </page>
</login>
